"use client";

import { useEffect, useState } from "react";
import { IMG, events, gallery, heroSlides, homeEvents, news, teachers } from "../data/siteData";
import { CardGrid, CTA, PageHero, SectionTitle, Stats, Testimonials, Link } from "../components/SiteComponents";

export function Home({ go }) {
  const [slide, setSlide] = useState(0);
  useEffect(() => {
    const nextImage = new Image();
    nextImage.src = heroSlides[(slide + 1) % heroSlides.length];
    const timer = setInterval(() => setSlide((current) => (current + 1) % heroSlides.length), 5000);
    return () => clearInterval(timer);
  }, [slide]);
  const features = [
    ["✦","Waxbarasho Tayo Leh","Manhaj dhammaystiran iyo hab waxbarid casri ah oo ardayga siiya saldhig aqooneed adag."],
    ["♟","Macallimiin Khibrad Leh","Macallimiin aqoon iyo waayo-aragnimo leh oo arday kasta si dhow u hagaya."],
    ["♡","Tarbiyad Wanaagsan","Waxaan kobcinnaa akhlaaqda, ixtiraamka iyo masuuliyadda ardayga."],
    ["⌂","Deegaan Casri ah","Goob waxbarasho oo ammaan ah, nadiif ah, kuna habboon barashada iyo hal-abuurka."],
    ["↗","Horumarinta Kartida","Arday kasta waxaan ka caawinnaa inuu ogaado oo kobciyo hibadiisa gaarka ah."],
    ["★","Natiijooyin Wanaagsan","Diyaargarow joogto ah iyo dabagal dhow oo horseeda guulo waxbarasho oo muuqda."],
  ];
  return <>
    <section className="hero"><div className="hero-slides" aria-hidden="true">{heroSlides.map((image,index)=><div key={image} className={`hero-bg ${slide===index?"active":""}`} style={{backgroundImage:`linear-gradient(90deg,rgba(4,30,65,.95) 0%,rgba(4,30,65,.74) 48%,rgba(4,30,65,.12) 100%),url('${image}')`}}></div>)}</div><div className="wrap hero-in"><div className="hero-copy" key={slide}><div className="pill">Tan iyo 2010 • Wadajir, Muqdisho</div><h1>Ku Soo Dhawoow <em>CARE</em> Primary and Secondary School</h1><p>Waxbarasho Tayo Leh, Tarbiyad Wanaagsan iyo Mustaqbal Iftiimaya</p><div className="actions"><Link to="/nagu-saabsan" onGo={go} className="btn gold">Wax Badan Ka Ogow <b>→</b></Link><Link to="/xiriir" onGo={go} className="btn ghost">Nala Soo Xiriir</Link></div></div><div className="hero-note"><span>Jiilka Berri</span><strong>Halkan ayuu ka bilaabmaa.</strong></div><div className="hero-dots" aria-label="Dooro sawirka weyn">{heroSlides.map((_,index)=><button key={index} className={slide===index?"active":""} onClick={()=>setSlide(index)} aria-label={`Sawirka ${index+1}`} aria-current={slide===index?"true":undefined}></button>)}</div></div></section>
    <Stats />
    <section className="section home-reveal"><div className="wrap split"><div className="image-stack"><img src={IMG.about} alt="Ardayda CARE School"/><div className="year"><b>15+</b><span>Sano oo adeeg waxbarasho ah</span></div></div><div><SectionTitle eyebrow="NAGU SAABSAN" title="Aqoonta iyo anshaxa ayaan si wadajir ah u dhisnaa."/><p className="lead">CARE Primary and Secondary School waa dugsi u taagan bixinta waxbarasho tayo leh iyo tarbiyad wanaagsan. Dugsigu wuxuu dadaal weyn geliyaa horumarinta aqoonta, anshaxa iyo kartida ardayda.</p><div className="ticks"><span>✓ Manhaj dhammaystiran</span><span>✓ Daryeel arday oo joogto ah</span><span>✓ Iskaashi waalid iyo dugsi</span><span>✓ Deegaan ammaan ah</span></div><Link to="/nagu-saabsan" onGo={go} className="text-link">Baro sheekadeenna <b>→</b></Link></div></div></section>
    <section className="section soft home-reveal"><div className="wrap"><SectionTitle eyebrow="MAXAA NALOO DOORTAA?" title="Meel uu arday walba ku kobco" text="Waxaan isku darnaa aqoon, tarbiyad iyo daryeel si aan ardayda ugu diyaarinno mustaqbalka."/><div className="feature-grid">{features.map(([i,t,d],x)=><article className="feature" style={{"--delay":`${x*.07}s`}} key={t}><span>{i}</span><div><small>0{x+1}</small><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
    <section className="section home-reveal"><div className="wrap"><SectionTitle eyebrow="DHACDOOYINKA DUGSIGA" title="Dhacdooyinka Ugu Muhiimsan" text="Daawo hawlaha waxbarasho, munaasabadaha iyo guulaha ardayda CARE."/><CardGrid data={homeEvents} type="event"/><div className="center"><Link to="/dhacdooyinka" onGo={go} className="btn navy">Dhammaan Dhacdooyinka →</Link></div></div></section>
    <Testimonials />
    <CTA go={go}/>
  </>;
}

export function About({go}) { const values=[["A","Aqoon","Waxbarasho qoto dheer oo fure u ah horumarka."],["A","Anshax","Akhlaaqda wanaagsan waa udub-dhexaadka bulshada."],["M","Mas'uuliyad","Qof walba wuxuu leeyahay door iyo waajib cad."],["H","Hal-abuur","Fikir cusub iyo xal-abuur ayaan dhiirrigelinnaa."],["I","Iskaashi","Waalid, arday iyo macallin oo isku duuban."],["H","Horumar","Maalin kasta tallaabo cusub oo hore loo qaado."]]; return <><PageHero eyebrow="CARE SCHOOL" title="Nagu Saabsan" text="Sheekada dugsi ku dhisan aqoon, anshax iyo himilo fog."/><section className="section"><div className="wrap split"><div><SectionTitle eyebrow="TAARIIKHDEENNA" title="Safar waxbarasho oo billowday 2010"/><p className="lead">CARE Primary and Secondary School waxaa la aasaasay sanadkii 2010, iyadoo ujeeddadu ahayd in carruurta Soomaaliyeed loo abuuro fursad waxbarasho oo tayo leh, la awoodi karo, kuna salaysan dhaqankeenna wanaagsan.</p><p>Sanadihii la soo dhaafay, dugsigu wuxuu noqday xarun waxbarasho oo lagu kalsoon yahay. Waxaan maalin kasta horumarinaynaa manhajka, xirfadda macallimiinta iyo deegaanka waxbarasho si ardaygu u helo meel uu ku fekero, ku tijaabiyo, kuna guulaysto.</p></div><div className="image-stack"><img src={IMG.primary} alt="Arday wax baranaya"/><div className="year"><b>2010</b><span>Bilowgii safarkeenna</span></div></div></div></section><section className="section navy-block"><div className="wrap mission-grid"><article><span>01</span><h2>Himiladeenna</h2><p>Inaan bixinno waxbarasho tayo sare leh oo dhisaysa aqoonta, akhlaaqda, kalsoonida iyo kartida arday kasta.</p></article><article><span>02</span><h2>Aragtideenna</h2><p>Inaan noqonno dugsi hormuud u ah tayada waxbarashada Soomaaliya, soona saara jiil mas'uul ah oo hal-abuur leh.</p></article></div></section><section className="section soft"><div className="wrap"><SectionTitle eyebrow="WAXAAN AAMINSANAHAY" title="Qiimaha nagu hagaya"/><div className="value-grid">{values.map(([l,t,d])=><article><span>{l}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section><CTA go={go}/></> }

export function Academics({go}) { const subjects=[["∑","Xisaab"],["S","Af-Soomaali"],["E","Af-Ingiriisi"],["ع","Af-Carabi"],["⚗","Saynis"],["◎","Cilmiga Bulshada"],["☾","Diinta Islaamka"],["⌘","Kombiyuutar"]]; return <><PageHero eyebrow="BARNAAMIJYADA" title="Waxbarashada" text="Manhaj dhammaystiran oo ardayda u diyaariya nolosha, jaamacadda iyo mustaqbalka."/><section className="section"><div className="wrap academic-grid"><article className="academic-card"><img src={IMG.primary} alt="Waxbarashada hoose"/><div><small>FASALLADA 1–8</small><h2>Dugsiga Hoose & Dhexe</h2><p>Waxaan dhisnaa aasaas adag oo akhris, qoraal, xisaab iyo faham ah; iyadoo ciyaar, su'aalo iyo hawlo wadajir ahi ka dhigayaan waxbarashada mid xiiso leh.</p><ul><li>Aasaas aqooneed oo adag</li><li>Tarbiyad iyo anshax</li><li>Kormeerka horumarka ardayga</li></ul></div></article><article className="academic-card"><img src={IMG.secondary} alt="Waxbarashada sare"/><div><small>FASALLADA 9–12</small><h2>Dugsiga Sare</h2><p>Ardayda waxaan siinnaa aqoon qoto dheer, xirfado fikir iyo diyaargarow imtixaan oo u sahlaya jaamacad iyo nolol shaqo oo guul leh.</p><ul><li>Diyaargarow imtixaan qaran</li><li>Hagid waxbarasho iyo xirfadeed</li><li>Shaybaar iyo tiknoolajiyad</li></ul></div></article></div></section><section className="section soft"><div className="wrap"><SectionTitle eyebrow="MAADOOYINKA" title="Aqoon ballaaran, xirfado waara" text="Maaddo kasta waxaa dhigaya macallimiin khibrad leh, iyadoo casharradu isku daraan aragti iyo ku-dhaqan."/><div className="subjects">{subjects.map(([i,s])=><div><span>{i}</span><b>{s}</b></div>)}</div></div></section><CTA go={go}/></> }

export function Teachers() { return <><PageHero eyebrow="KOOXDEENNA" title="Macallimiinta" text="Baro dadka aqoonta, daryeelka iyo dhiirrigelinta maalin kasta la garab taagan ardaydeenna."/><section className="section leadership-section"><div className="wrap"><div className="leadership"><div className="leadership-photo"><img src="/images/mohamed-omar.jpeg" alt="Mohamed Omar, maamulka CARE School"/><span>MAAMULKA DUGSIGA</span></div><div className="leadership-message"><span className="quote-mark">“</span><SectionTitle eyebrow="FARIINTA MAAMULKA" title="Waxbarashadu waa saldhigga mustaqbal ifaya"/><p className="lead">Ku soo dhowaada CARE Primary and Secondary School. Waxaan aaminsanahay in arday kasta uu leeyahay karti u gaar ah oo u baahan hagid, dhiirrigelin iyo deegaan waxbarasho oo ammaan ah.</p><p>Hadafkeennu waa inaan dhisno jiil aqoon leh, anshax wanaagsan leh, kuna kalsoon awooddiisa. Waxaan si dhow ula shaqaynaa macallimiinta, waalidiinta iyo ardayda si aan u xaqiijinno waxbarasho tayo leh iyo horumar joogto ah.</p><div className="leadership-signature"><b>Mohamed Omar</b><small>Maamulka CARE School</small></div></div></div><div className="admin-team"><article className="admin-card"><img src="/images/aweys-abshir-cabdi.png" alt="Aweys Abshir Cabdi, Admin and Finance"/><div><small>ADMIN AND FINANCE</small><h3>Aweys Abshir Cabdi</h3></div></article><article className="admin-card"><img src="/images/abuukar-maxamed-xasan.jpeg" alt="Abuukar Maxamed Xasan, President of School"/><div><small>PRESIDENT OF SCHOOL</small><h3>Abuukar Maxamed Xasan</h3></div></article></div></div></section><section className="section soft"><div className="wrap"><SectionTitle eyebrow="MACALLIMIINTA CARE" title="Khubaro qalbi waxbarid leh" text="Macallin kasta wuxuu ardayda ku hagaa aqoon, anshax iyo karti ay mustaqbalkooda ku dhistaan."/><div className="teacher-grid">{teachers.map(([n,r,img])=><article className="teacher" key={n}><div className="teacher-img"><img src={img} alt={`${n}, ${r}`}/></div><small>{r==="Xisaabiye"?"XISAABIYE":`MACALLINKA ${r}`}</small><h3>{n}</h3></article>)}</div></div></section></> }

export function Events(){return <><PageHero eyebrow="JADWALKA DUGSIGA" title="Dhacdooyinka Dugsiga" text="La soco munaasabadaha, tartamada iyo kulamada muhiimka ah ee bulshadeenna waxbarasho."/><section className="section"><div className="wrap"><CardGrid data={events} type="event"/></div></section></>}

export function GalleryPage(){const [filter,setFilter]=useState("Dhammaan"); const [modal,setModal]=useState(null); const cats=["Dhammaan","Ardayda","Macallimiinta","Xafladaha","Fasallada","Tartamada","Hawlaha Dugsiga"]; const shown=filter==="Dhammaan"?gallery:gallery.filter(x=>x[0]===filter); useEffect(()=>{const f=e=>e.key==="Escape"&&setModal(null);addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);return <><PageHero eyebrow="XUSUUSAHEENNA" title="Sawirrada Dugsiga" text="Muuqaallo ka tarjumaya waxbarashada, farxadda iyo wadajirka CARE School."/><section className="section"><div className="wrap"><div className="filters">{cats.map(c=><button key={c} className={filter===c?"active":""} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="gallery-grid">{shown.map(([c,img],i)=><button key={img} onClick={()=>setModal([c,img])} className={`gallery-item g${i%5}`}><img loading="lazy" decoding="async" src={img} alt={c}/><span><b>{c}</b><i>+ Daawo</i></span></button>)}</div></div></section>{modal&&<div className="lightbox" onClick={()=>setModal(null)} role="dialog" aria-modal="true"><button aria-label="Xir">×</button><img src={modal[1]} alt={modal[0]}/><span>{modal[0]}</span></div>}</>}

export function News(){return <><PageHero eyebrow="WARGELINTA" title="Wararkii Ugu Dambeeyay" text="Akhri guulaha ardayda, horumarka dugsiga iyo wararka cusub ee CARE School."/><section className="section"><div className="wrap"><CardGrid data={[...news,...events.slice(0,3)]} type="news"/></div></section></>}

export function Contact(){function submit(e){e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);const message=`Fariin cusub oo ka timid website-ka CARE School\n\nMagaca: ${data.get("name")}\nTelefoonka: ${data.get("phone")}\nIimaylka: ${data.get("email")}\nMawduuca: ${data.get("subject")}\n\nFariinta:\n${data.get("message")}`;window.open(`https://wa.me/252616460649?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer");}return <><PageHero eyebrow="WADA HADAL" title="Nala Soo Xiriir" text="Su'aal ma qabtaa? Kooxdayadu waxay diyaar u tahay inay ku caawiso."/><section className="section"><div className="wrap contact-grid"><div><SectionTitle eyebrow="XOGTA XIRIIRKA" title="Waxaan jeclaan lahayn inaan kaa maqalno."/><p className="lead">Nagu soo booqo Jidka Afgooye, Wadajir ama naga soo wac lambarka dugsiga. Waxaan ku siin doonnaa macluumaadka diiwaangelinta iyo waxbarashada.</p><div className="contact-list"><div><span>📍</span><p><b>Goobta</b>27PW+HJG, Jidka Afgooye, Wadajir, Muqdisho</p></div><div><span>☎</span><p><b>Telefoonka</b>0616460649</p></div><div><span>⌂</span><p><b>Ururka Waxbarashada</b>Midowga Dugsiyada Gobolka Banaadir</p></div></div></div><form onSubmit={submit}><div className="form-head"><span>FARIIN NOO SOO DIR</span><h2>Sideen kuu caawin karnaa?</h2></div><div className="form-row"><label>Magaca<input required name="name" placeholder="Magaca oo buuxa"/></label><label>Telefoonka<input required name="phone" type="tel" placeholder="0616460649"/></label></div><label>Iimaylka<input required name="email" type="email" placeholder="magac@tusaale.com"/></label><label>Mawduuca<input required name="subject" placeholder="Maxay fariintu ku saabsan tahay?"/></label><label>Fariinta<textarea required name="message" rows="5" placeholder="Halkan ku qor fariintaada..."></textarea></label><button className="btn gold" type="submit">WhatsApp ku Dir →</button></form></div></section><section className="map"><div><span>📍</span><b>CARE Primary and Secondary School</b><small>Jidka Afgooye, Wadajir, Muqdisho</small></div></section></>}
